version: "3"

services:

  network-db:
    image: postgres:14.5-alpine
    restart: "no"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=sulgik
      - POSTGRES_PASSWORD=supersulgik
    ports:
      - "5432:5432"

  network:
    image: sulgeran/recordgram-server
    restart: "no"
    volumes:
      - ./config.yaml:/app/go-sample-app/config.yaml
    ports:
      - "8080:8080"